# -*- coding: utf-8 -*-
"""MySQL 服务器变量中文含义词典(来源: MySQL 官方文档 server-system-variables)。
覆盖高频常用变量;未收录的走 fallback。离线、零网络依赖。"""

_KNOWN = {
    "max_connections": "最大允许的并发客户端连接数",
    "max_connect_errors": "某主机最大连接错误次数,超过后该主机被阻塞",
    "connect_timeout": "服务器等待连接包的超时秒数",
    "wait_timeout": "非交互连接空闲多久后断开(秒)",
    "interactive_timeout": "交互式连接空闲多久后断开(秒)",
    "net_read_timeout": "等待从客户端读取数据的超时秒数",
    "net_write_timeout": "等待向客户端写数据的超时秒数",
    "innodb_buffer_pool_size": "InnoDB 缓冲池大小(缓存表与索引的内存,越大命中率越高)",
    "innodb_buffer_pool_instances": "InnoDB 缓冲池分片实例数",
    "innodb_flush_log_at_trx_commit": "事务提交时日志刷盘策略(0/1/2,1 最安全影响性能)",
    "innodb_log_file_size": "InnoDB 重做日志单个文件大小",
    "innodb_log_buffer_size": "InnoDB 重做日志缓冲大小",
    "innodb_file_per_table": "每张表独立表空间(默认ON)",
    "innodb_flush_method": "InnoDB 数据刷盘方式(fsync/O_DSYNC/littlesync等)",
    "innodb_lock_wait_timeout": "InnoDB 行锁等待超时(秒)",
    "innodb_io_capacity": "InnoDB 后台刷脏页/合并的 I/O 能力上限",
    "innodb_io_capacity_max": "InnoDB 后台 I/O 能力上限的高水位",
    "key_buffer_size": "MyISAM 键缓存大小(MyISAM 索引用/缓冲)",
    "query_cache_size": "查询缓存大小(8.0 已移除,恒为0)",
    "query_cache_type": "查询缓存类型(8.0 已移除,恒为OFF)",
    "sort_buffer_size": "排序缓冲区大小(单线程排序用,连接级)",
    "join_buffer_size": "连接(join)缓冲区大小(连接级)",
    "read_buffer_size": "对 MyISAM 顺序扫表时的读缓冲(连接级)",
    "read_rnd_buffer_size": "随机读缓冲(ORDER BY 后按行读用,连接级)",
    "tmp_table_size": "内存临时表大小上限,超限转磁盘临时表",
    "max_heap_table_size": "内存临时表(MEMORY/HEAP)最大大小",
    "max_allowed_packet": "一次最大包大小(影响大字段/批量导入)",
    "thread_cache_size": "线程缓存数,减少线程创建开销",
    "thread_stack": "每个线程的栈大小",
    "sql_mode": "SQL 模式(影响语法与数据校验,如 STRICT_TRANS_TABLES)",
    "character_set_server": "服务器默认字符集",
    "character_set_client": "客户端发送字符集",
    "character_set_connection": "连接层字符集(转码用)",
    "character_set_results": "结果集返回字符集",
    "collation_server": "服务器默认排序规则(校验集)",
    "collation_connection": "连接级排序规则",
    "time_zone": "服务器时区(OFFSET或SYSTEM)",
    "system_time_zone": "系统时区",
    "autocommit": "是否默认自动提交事务(ON/OFF)",
    "transaction_isolation": "默认事务隔离级别(REPEATABLE-READ等)",
    "tx_isolation": "transaction_isolation 的别名(旧)",
    "log_bin": "是否开启二进制日志(ON/OFF,用于复制与PITR)",
    "binlog_format": "二进制日志格式(ROW/STATEMENT/MIXED)",
    "max_binlog_size": "单个二进制日志文件最大大小",
    "expire_logs_days": "二进制日志保留天数(8.0 起建议 binlog_expire_logs_seconds)",
    "binlog_expire_logs_seconds": "二进制日志过期秒数",
    "slow_query_log": "是否开启慢查询日志(ON/OFF)",
    "long_query_time": "超过该秒数的查询记录为慢查询",
    "slow_query_log_file": "慢查询日志文件路径",
    "log_queries_not_using_indexes": "是否记录未使用索引的查询",
    "general_log": "是否开启通用日志(记录所有语句,默认OFF)",
    "general_log_file": "通用日志文件路径",
    "performance_schema": "是否启用 performance_schema",
    "thread_handling": "线程处理方式(one-thread-per-connection/no-threads)",
    "have_ssl": "是否支持 SSL(ENABLED/DISABLED)",
    "ssl_ca": "SSL CA 证书文件路径",
    "ssl_cert": "SSL 服务器证书文件路径",
    "ssl_key": "SSL 私钥文件路径",
    "datadir": "数据目录路径",
    "basedir": "MySQL 安装目录",
    "tmpdir": "临时文件目录",
    "pid_file": "PID 文件路径",
    "socket": "Unix socket 文件路径(仅类Unix)",
    "port": "服务器监听端口",
    "bind_address": "服务器监听地址",
    "skip_name_resolve": "是否跳过域名反解析(ON 提升连接性能)",
    "secure_file_priv": "LOAD DATA/导出文件允许的目录(空=不限制)",
    "lower_case_table_names": "表名大小写敏感策略(0/1/2,影响跨平台迁移)",
    "table_open_cache": "打开表的缓存数量上限",
    "table_definition_cache": "表定义缓存数量",
    "open_files_limit": "服务器最大打开文件数",
    "back_log": "监听队列长度(连接峰值时避免丢失)",
    "max_used_connections": "历史最大并发连接数(峰值)",
    "sync_binlog": "每写多少事务将 binlog 落盘(1 最安全)",
    "innodb_stats_on_metadata": "访问元数据是否触发统计数据更新",
    "group_concat_max_len": "GROUP_CONCAT() 结果最大长度",
    "lc_time_names": "日期/月份名称语言(locale)",
    "init_connect": "客户端连接时执行的初始化 SQL(可用于 set 会话变量)",
    "default_storage_engine": "默认存储引擎(InnoDB)",
    "default_authentication_plugin": "默认认证插件(caching_sha2_password等)",
    "password_history": "禁止重用旧密码的历史数",
    "validate_password_length": "密码校验:最小长度(需 validate_password 组件)",
    "audit_log_file": "审计日志文件(需 audit_log 插件)",
}

_DEFAULT = ""  # 未收录/无法给出准确含义的变量,留空(不引用官方文档)


def describe(name: str) -> str:
    """返回变量中文含义;未收录返回通用指引。"""
    return _KNOWN.get(name, _DEFAULT)


def known_dict():
    return dict(_KNOWN)